# Generated by Django 2.2 on 2019-04-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20190417_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group',
        ),
    ]
