# Generated by Django 2.2 on 2019-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20190514_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('N/A', 'N/A')], default='PG-13', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
