# Generated by Django 2.2 on 2019-05-19 18:58

from django.db import migrations, models
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20190514_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[ratings.models.validate_rating]),
        ),
    ]
