# Generated by Django 2.2 on 2019-04-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.DateField()),
                ('runtime_minutes', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=40, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('plot', models.TextField(null=True)),
                ('poster_link', models.CharField(max_length=200, null=True)),
                ('imdb_rating', models.FloatField(null=True)),
                ('rt_rating', models.IntegerField(null=True)),
                ('added_to_db', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=120)),
                ('invitation_count', models.IntegerField(default=0)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='testing.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('comment', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testing.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='testing.User')),
            ],
        ),
    ]
