# Generated by Django 2.2 on 2019-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190410_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
