# Generated by Django 2.2 on 2019-04-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group',
        ),
    ]
